export const SET_USER = 'SET_USER';
export const SET_USER_DETAILS = 'SET_USER_DETAILS';
export const SET_USER_DETAILS_SUCCESS = 'SET_USER_DETAILS_SUCCESS';
export const USER_LOADING = 'USER_LOADING';
